"""Add cascade

Revision ID: defb1f9a88b1
Revises: 
Create Date: 2023-08-10 21:23:30.131114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defb1f9a88b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='menu_pkey'),
    sa.UniqueConstraint('title', name='menu_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('submenu',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='submenu_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='submenu_pkey'),
    sa.UniqueConstraint('title', name='submenu_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dish',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submenu_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], name='dish_submenu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dish_pkey'),
    sa.UniqueConstraint('title', name='dish_title_key')
    )
    # ### end Alembic commands ###
